- name: install base items
  ansible.builtin.package:
    name: "{{ item }}"
    state: present
  with_items:
    - git
    - python3
    - python3-pip
    - python3-venv
    - apt-transport-https
    - ca-certificates
    - curl
    - gnupg-agent
    - software-properties-common
    - openjdk-11-jdk

- name: GPG key
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present

- name: add docker repo to apt 
  apt_repository:
    repo: deb https://download.docker.com/linux/ubuntu bionic stable
    state: present

- name: Update and install docker-ce
  apt: update_cache=yes name=docker-ce state=latest

- name: install docker python module
  pip:
    name: docker
