//varialbes 
//def scannerHome = tool 'SonarScanner 4.4.0.2170';	

pipeline{ 
	agent {
		label 'worker_node_1'
	}
	
	stages {
		
		stage('static analysis'){
			environment {
				SCANNERHOME =  tool 'Sonar_1'

			}
			steps {
				//def scannerHome = tool 'SonarScanner 4.4.0.2170';	
				withSonarQubeEnv('sonarcloud_1') {
					
    			sh '''
					sonar-scanner \
  					-Dsonar.organization=matthew-cradit-1 \
  					-Dsonar.projectKey=matthew-cradit_flask_project \
  					-Dsonar.sources=. \
  					-Dsonar.host.url=https://sonarcloud.io
					'''
				}
			}	
		}
		stage('build python code'){
			agent{
				docker{
					image 'python:3-alpine'
				}
			}
			steps{
				sh 'python -m py_compile sources/web_app.py'
				stash(name: 'compiled-results', includes:'sources/*.py*')
			}
		}

		stage('test code'){
			agent{
				docker{
					image 'mc993/flask-pytest:0.0.1'
				}
			}
			steps{
				
				sh 'py.test --junit-xml test-reports/results.xml sources/test_web_app.py'
			}
			post{
				always{
					junit 'test-reports/results.xml'
				}
			}
		}
	}
	post{
		always {
			withCredentials([string(credentialsId: 'Discord_webhook_ks', variable: 'discord_webhook_url')]){
				discordSend description: "Flask_project (ノಠ益ಠ)ノ彡┻━┻ \n \n job: $JOB_NAME \n status: ${currentBuild.currentResult} \n BuildID: $BUILD_ID",
					footer: "End of Tansmission",
					link: env.BUILD_URL,
					result: currentBuild.currentResult,
					thumbnail: 'https://cdn.discordapp.com/attachments/859942982425378817/862792459900944415/jenkins-icon-Matthew-Cradit.png',
					title: JOB_NAME,
					webhookURL: "$discord_webhook_url"
			}
		}
	}
}

