//varialbes 
//def scannerHome = tool 'SonarScanner 4.4.0.2170';	

pipeline{ 
	agent {
		label 'worker_node_1'
	}
	
	stages {
	
		stage('test code'){
			agent{
				docker{
					image 'mc993/flask-pytest:0.0.3'
				}
			}
			environment{
				USER_NAME='test'
				USER_PASS='test'
			}
		
			steps{
											
				sh 'pytest --junit-xml test-reports/results.xml sources/'
			}
			post{
				always{
					junit 'test-reports/results.xml'
				}
			}
		}
	
		stage('static analysis'){
			environment {
				SCANNERHOME =  tool 'Sonar_1'

			}
			steps {
				//def scannerHome = tool 'SonarScanner 4.4.0.2170';	
				withSonarQubeEnv('sonarcloud_1') {
					
    			sh '''
					${SCANNERHOME}/sonar-scanner-4.4.0.2170-linux/bin/sonar-scanner\
  					-Dsonar.organization=matthew-cradit-1 \
  					-Dsonar.projectKey=matthew-cradit_flask_project \
  					-Dsonar.sources=. \
  					-Dsonar.host.url=https://sonarcloud.io
					'''
				}
			}	
		}

		stage('wait for quality gate'){
			steps{
				waitForQualityGate abortPipeline: true
			}
		}

	}
	post{
		always {
			withCredentials([string(credentialsId: 'Discord_webhook_ks', variable: 'discord_webhook_url')]){
				discordSend description: "Flask_project (ノಠ益ಠ)ノ彡┻━┻ \n \n job: $JOB_NAME \n status: ${currentBuild.currentResult} \n BuildID: $BUILD_ID",
					footer: "End of Tansmission",
					link: env.BUILD_URL,
					result: currentBuild.currentResult,
					thumbnail: 'https://cdn.discordapp.com/attachments/859942982425378817/862792459900944415/jenkins-icon-Matthew-Cradit.png',
					title: JOB_NAME,
					webhookURL: "$discord_webhook_url"
			}
		}
	}
}

