---

- hosts: all
  become: true 
  pre_tasks:
    
    - name: update repos (CentrOS)
      tags: always
      dnf:
        update_cache: yes
      
      when: ansible_distribution == "CentOS"

    - name: update repos (Ubuntu)
      tags: always
      apt:
        update_cache: yes
        #change_when: false
      when: ansible_distribution == "Ubuntu"
      
- hosts: all
  become: true
  roles:
    - base

- hosts: jenkins
  become: true
  roles:
    - jenkins_node


  
